### ISSUE TITLE
png2zx dependencies

### ISSUE THREAD

**Issue by vitasam** [alemorf/zx_spectrum_game#2]
Вопрос - **png2zx** зависит от libpng12.so.0, которой уже нет в Ubuntu, начиная от 16.04. Откуда берут **png2zx** утилиту, нельзя ли ее из исходников пересобрать?

**Comment by alemorf** [comment]
добавил исходники, собираются автоматически при make

**Comment by vitasam** [comment]
Все сбилдилось, спасибо.
Какой из эмуляторов Spectrum 128 под Windows посоветуете?

**Comment by alemorf** [comment]
Вчера я попробовал Unreal Speccy:

http://dlcorp.nedopc.com/viewforum.php?f=27

А до этого пользовался универсальным эмулятором. Он несколько десятков компьютеров эмулирует:

http://bashkiria-2m.narod.ru/files/emu.rar

**Comment by vitasam** [comment]
Спасибо, запустил lsttrial.trd под Unreal Speccy
